name: Update Homebrew Formulas

on:
  schedule:
    - cron: '0 20 * * *'  # 每天执行一次 北京时间 4:00
  workflow_dispatch:     # 手动触发
    inputs:
      force_update:
        description: "是否忽略版本检查强制更新 (yes/no)"
        required: false
        default: "no"

jobs:
  update-formulas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Update Homebrew
        run: brew update

      - name: Install jq
        run: brew install jq
        
      - name: Check and update formulas
        run: |
          # 获取输入参数，检查是否强制更新
          force_update="${{ github.event.inputs.force_update }}"
          echo "Force update: $force_update"

          # 遍历 Formula 和 Cask 目录中的 .rb 文件
          for formula_file in ./Formulas/*.rb ./Casks/*.rb; do
            # 检查文件是否存在，并检测文件类型（Cask 或 Formula）
            if [[ -f "$formula_file" ]]; then
              if [[ "$formula_file" == *"/Casks/"* ]]; then
                file_type="cask"
              elif [[ "$formula_file" == *"/Formulas/"* ]]; then
                file_type="formula"
              else
                echo "Skipping unknown file location: $formula_file"
                continue
              fi
            else
              continue
            fi

            # 提取公式名称
            formula_name=$(basename "$formula_file" .rb)
            echo "Checking $formula_name..."

            # 获取当前版本
            current_version=$(grep -E 'version "[^"]+"' "$formula_file" | sed 's/.*"\([^"]*\)".*/\1/')
            
            # 查询最新版本
            if [[ "$file_type" == "cask" ]]; then
              latest_version=$(brew livecheck --cask "$formula_name" --json | jq -r '.[0].version.latest')
            elif [[ "$file_type" == "formula" ]]; then
              latest_version=$(brew livecheck "$formula_name" --json | jq -r '.[0].version.latest')
            fi

            if [[ -z "$latest_version" || "$latest_version" == "null" || -z "$current_version" ]]; then
              echo "Error: Unable to fetch version information for $formula_name. Skipping..."
              continue
            fi

            echo "Latest version: $latest_version, Current version: $current_version"

            # 判断是否强制更新
            if [[ "$force_update" == "yes" || "$latest_version" != "$current_version" ]]; then
              echo "Updating $formula_name to version $latest_version..."

              # 构建新的下载链接
              url=$(grep -E 'url ".*"' "$formula_file" | sed 's/.*"\(.*\)".*/\1/' | sed "s/#{version}/$latest_version/")
              
              # 打印下载链接
              echo "Download URL: $url"

              # 下载文件并计算 sha256
              curl -L "$url" -o /tmp/source.tar.gz
              ls -lh /tmp/source.tar.gz  # 打印文件大小，检查下载是否成功
              
              # 计算文件的 sha256 值
              new_sha256=$(shasum -a 256 /tmp/source.tar.gz | awk '{print $1}')
              echo "Computed sha256: $new_sha256"

              # 更新版本号和 sha256
              sed -i "s/version \"$current_version\"/version \"$latest_version\"/" "$formula_file"
              sed -i "s/sha256 \".*\"/sha256 \"$new_sha256\"/" "$formula_file"

              echo "$formula_name updated: version $latest_version, sha256 $new_sha256"

              # 添加变更
              git add "$formula_file"
            else
              echo "$formula_name is up-to-date."
            fi
          done

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if git diff --cached --exit-code; then
            echo "No updates found."
          else
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
            git commit -m "Update formulas to latest versions"
            git push origin HEAD:${{ github.ref_name }}
          fi